### ISSUE TITLE
Issue with Streamlit “Wide Mode” in Labeling Section

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#100]
Description:

When disabling “Wide Mode” from Streamlit’s settings, the video section from Labeling gets compressed in the middle and the video panes/video descriptions overlap and some longer channel names might no longer be displayed in their designated box.

Only the Labeling section appears to be affected by this.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Signup for an account or log in using an existing account.
3. Access the Labeling section
4. From the menu in the top right, select Settings and disable “Wide Mode”
5. Notice that the videos and video descriptions got compressed in the middle and now overlap. The longer channel names will also spill out from their designated box.

Actual:
Disabling “Wide Mode” causes display issues on the Labeling section page.

Expected:
Disabling “Wide Mode” should not cause UI overlaps and spillage.

https://user-images.githubusercontent.com/50236075/163127322-566f54f0-3f1c-4d46-a5de-fe704ed0aede.mp4

**Comment by iRanadheer** [comment]
Hey @acornestean,

Unfortunately, to be able to display both the videos and their details next to each other, the app has to be set in a wide mode. Because we have written some embedding code in HTML to embed the videos and other details. We can't possibly know whether the user has selected or deselected the wide mode on browser settings.

**Comment by iRanadheer** [comment]
I will close this issue, please re-open if needed
