### ISSUE TITLE
Extension pop-up is stuck at “Loading...” if one clicks the add-on icon before the video loads

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#3]
Preconditions:
1. RegretsReporter is installed

Steps to reproduce:
1. Access YouTube and immediately as a video can be clicked, click on it
2. Before the video loads (the video playback area is black/blank) click on the add-on icon 
3. Notice that the pop-up will remain stuck at “Loading...”

Expected results:
The reporting process should proceed normally i.e. the pop-up should display the appropriate UI in order to file a report.

Actual results:
The extension pop-up is stuck at “Loading...”.

Affected versions:

Firefox
- Beta 81.0b8/20200908191057
- Release 80.0.1/20200831163820

Google Chrome
- Chrome 85.0.4183.102

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS
- macOS 10.15

![stuck at loading](https://user-images.githubusercontent.com/50236075/92745709-444b2300-f38b-11ea-9b68-6324297d354e.gif)

**Comment by motin** [comment]
Technically, this happens when the user clicks the add-on icon after the navigation to the watch page has been requested but before the HTTP response for the video information has been received. 

There are two issues here:
1. The user should see a more informative message rather than just "Loading..."
2. The "Loading..." bar / notice is shown even after the video has loaded and the user clicks the icon anew.

Two fixes have been issued:
1. I have changed the behavior to show a popup with information that one needs to wait for the video to finish loading (via 9bdb0af0c48ae55dfdaab654f6e8f19cc8a9a339)
2. I have made sure that the report form, rather than the loading info, is shown (via https://github.com/mozilla-extensions/regrets-reporter/commit/5b890a45aa82aa61ff85478affd5438b2f663861)

**Comment by acornestean** [comment]
Verified the fix with add-on version 0.9.9 on Chrome (85.0.4183.102), Beta Developer Edition (81.0b9/20200910180444) and Unbranded Release (80.0.1/20200831163820) under Windows 10 Pro 64-bit and Ubuntu 16.04 LTS.

On Chrome a popup with information that one needs to wait for the video to finish loading or refresh the page is displayed (see screenshot), when managing to perform the actions stated in the reproduction steps. Refreshing the page as instructed will allow the report form to be displayed as intended.

On Firefox, the panel loads alongside the video (sometimes even faster). In conclusion, the behavior mentioned above on Chrome could not be replicated on Firefox. From ~35 attempts the pop-up instructing to wait for the video to finish loading or refresh the page was not displayed, instead the report form loaded each time.

![2020-09-15_10h52_11](https://user-images.githubusercontent.com/50236075/93184636-2b54c000-f745-11ea-8010-6461ecd1cee0.png)
