### ISSUE TITLE
Pressing “Ctrl+Enter” when adding users does nothing

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/regrets-reporter#83]
Description:
After inputting usernames as part of the adding of users process, a tooltip is displayed in the username input field, at the bottom right corner, stating to “Press Ctrl+Enter to apply”. Pressing the shortcut does nothing.

Steps to reproduce:
1. Access http://94.3.209.235:8502/
2. Log in as admin
3. Select “User Management” from the “Choose your operation” drop down.
4. Input a username in the “Usernames” field
5. Notice the tooltip appearing at the bottom right corner of the field
6. Press Ctrl+Enter and notice it does nothing

Expected:
Pressing Ctrl+Enter should perform the same action as clicking the “Add users” button i.e. create a user with the previously input username.

Actual:
Pressing Ctrl+Enter does nothing.

https://user-images.githubusercontent.com/50236075/161050525-559a444c-b0d5-4c3f-a8a6-74776e40e9c6.mp4

**Comment by iRanadheer** [comment]
Hey @acornestean,

Thanks for raising the issue. The ctrl+ Enter is the streamlit help label that comes along with the widget. But the actual work happens when you click the Add Users button. I'll try to get rid of the streamlit help label meanwhile. Closing this issue for the moment, please re-open if needed.
